In [15]:
import numpy as np
from math import sqrt
from statistics import mean
n=int(input("enter no of variables"))
x=[]
for i in range(n):
  p=[int(x) for x in input().split(" ")]
  x.append(p)
print(x)

mu=[]
for i in range(n):
  mu.append(np.mean(x[i],axis=0))
print(mu)

n1=len(x[0])
si=[]
x=np.array(x)
for i in range(n):
  k=sum((x[i]-mu[i])**2)
  si.append(round(sqrt(k/(n1-1)),4))
print(si)
a=[]
for i in range(n):
  a.append((x[i]-mu[i])/si[i])
print(a)
A=np.transpose(a)
#variance covariance matrix
VarCov=np.dot(np.transpose(A),A)/n1
print('\nVariance Covariance Matrix is :\n {}'.format(VarCov))

eigenValues, eigenVectors = np.linalg.eig(VarCov)

idx = eigenValues.argsort()[::-1]
eigenValues = eigenValues[idx]
eigenVectors = eigenVectors[:,idx]

print('\nEigen Values are {}'.format(eigenValues))
print('\nEigen Vectors are {}'.format(eigenVectors))

#no of principal components to be retained
k=int(input("enter threshold limit :"))
s=sum(eigenValues)
t=[]
stoppoint=1
for i in range(len(eigenValues)):
    numerator=sum(eigenValues[0:i+1])
    z=(numerator/s)*100
    if z<=k:
        stoppoint=stoppoint+1
    t.append(z)
print('\nThreshold Table :\n{}'.format(t))

eigenValues=eigenValues[0:stoppoint]
eigenVectors=eigenVectors[:,0:stoppoint]

#retaining eigen values and vectors
print('\nRetained Eigen Values :\n{}'.format(eigenValues))
print('\nRetained Eigen Vectors: \n{}'.format(eigenVectors))
egv=np.transpose(eigenVectors)
f=[]

for i in range(len(egv)):
  o=[]
  for j in range(n):
    k=sqrt(eigenValues[i])*egv[i][j]
    o.append(k)
  f.append(o)
print(f)
h=[]
for i in range(len(f[0])):
  h.append(f[0][i]*2+f[1][i]*2)
print(h)
sumh=sum(h)
print(sumh)

pve=[]
for i in range(len(eigenValues)):
  pve.append((eigenValues[i]/sumh)*100)
print(pve)


enter no of variables3
3 7 10 3 10
6 3 9 9 6
5 3 8 7 5
[[3, 7, 10, 3, 10], [6, 3, 9, 9, 6], [5, 3, 8, 7, 5]]
[6.6, 6.6, 5.6]
[3.5071, 2.51, 1.9494]
[array([-1.02648912,  0.11405435,  0.96946195, -1.02648912,  0.96946195]), array([-0.23904382, -1.43426295,  0.9561753 ,  0.9561753 , -0.23904382]), array([-0.30778701, -1.33374372,  1.23114805,  0.71816969, -0.30778701])]

Variance Covariance Matrix is :
 [[ 0.80001623 -0.04089598  0.06435815]
 [-0.04089598  0.7999873   0.78479557]
 [ 0.06435815  0.78479557  0.79996624]]

Eigen Values are [1.58512447 0.80666111 0.0081842 ]

Eigen Vectors are [[ 0.02122114 -0.99538368 -0.09360014]
 [ 0.70624057  0.0811911  -0.70330098]
 [ 0.70765382 -0.05117936  0.7047033 ]]
enter threshold limit :99

Threshold Table :
[66.047684718041, 99.65898746868129, 100.0]

Retained Eigen Values :
[1.58512447 0.80666111]

Retained Eigen Vectors: 
[[ 0.02122114 -0.99538368]
 [ 0.70624057  0.0811911 ]
 [ 0.70765382 -0.05117936]]
[[0.026717780654088214, 0.889169065897646